### ISSUE TITLE
Extra HTML, CSS, JS files?

### ISSUE THREAD

**Issue by interrogator** [henokemp/university-work#1]
It looks to me like a lot of the files from local building have been committed into this project (i.e. the `site` directory). To the best of my knowledge, these should not be necessary and don't need to be committed, as readthedocs will generate your site for you. So if you want to, you could probably discard the `site` dir and the project would still build in the same way.

**Comment by henokemp** [comment]
Alright, let's try that.

**Comment by henokemp** [comment]
Worked fine! Closed issue.
